version: '3.7'

volumes:
    logs:
        driver: local
services:
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
            docerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        links:
            - mysql
    mysql:
        image: mysql:latest
        container_name: mysql
        restart: always
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - MYSQL_USERNAME=root
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=atower
        ports:
            - "8989:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8181:80"
        links:
            - mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=secret

